### ISSUE TITLE
how to activate

### ISSUE THREAD

**Issue by barlet4094** [mitchhymel/MusicBeeSyncToService#1] opened 2020-07-18 12:51 UTC
Can we please have instructions how to activate this plugin?

**Comment by mitchhymel** [comment] 2020-07-19 02:30
I've updated the [readme](https://github.com/mitchhymel/MusicBeeSyncToService/blob/master/readme.md) with more info, let me know if that clears things up.

**Comment by barlet4094** [comment] 2020-07-19 10:53
Thanks mithymel. Finally have got it to work although signing in to Spotify is producing the following error "Opening browser to log in to Spotify...
Could not load file or assembly 'Unosquare.Labs.EmbedIO, Version=2.9.2.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified."

I would like to synchronise Spotify is very important to me as it would solve a hell lot of problems.

**Comment by mitchhymel** [comment] 2020-07-19 19:54
Unfortunately, I'm not sure what the problem is and I don't have the same problem on my end. It looks like an older version of the plugin used embed.io 2.9.2.0, so my best guess is that you might have mismatched dlls from separate releases (i might have bumped nuget package versions in between releases).

Let me know if these steps fix anything:
1) Redownload latest release [(currently 3.1.0)](https://github.com/mitchhymel/MusicBeeSyncToService/releases/tag/3.1.0)
2) Since we're next going to copy and overwrite contents into musicbee plugins folder, copy all contents that currently exist in your musicbee plugins folder to another location as a backup
3) Copy all contents from the downloaded zip file into your musicbee plugins folder, making sure to overwrite files if they already exist

**Comment by barlet4094** [comment] 2020-07-20 08:21
Hi, thanks for you reply. Unfortunately there has been no joy in overwriting the contents of the plugin folder. I even tried it on a separate portable version (i.e. installed on a portable SSD) and still I got the same result. Thanks for your effort, all the same.

**Comment by mitchhymel** [comment] 2020-08-04 02:40
Since the initial issue is resolved, I'm closing this and tracking the "could not load file or assembly..." issue at #2

**Closed as completed by mitchhymel** 2020-08-04 02:40 UTC
